export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_LIST_ITEM_REQUEST = "CART_LIST_ITEM_REQUEST";

export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_LIST_ITEM_SUCCESS = "CART_LIST_ITEM_SUCCESS";

export const CART_ADD_ITEM_FAILS = "CART_ADD_ITEM_FAILS";
export const CART_REMOVE_ITEM_FAILS = "CART_REMOVE_ITEM_FAILS";
export const CART_LIST_ITEM_FAILS = "CART_LIST_ITEM_FAILS";

export const CART_INCREMENT_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_INCREMENT_ITEM_FAILS = "CART_ADD_ITEM_FAILS";
export const CART_INCREMENT_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
