export const CAT_FETCH_REQUEST = "CAT_FETCH_REQUEST";
export const CAT_FETCH_SUCCESS = "CAT_FETCH_SUCCESS";
export const CAT_FETCH_FAILS = "CAT_FETCH_FAILS";

export const CAT_FETCH_BY_ID_REQUEST = "CAT_FETCH_BY_ID_REQUEST";
export const CAT_FETCH_BY_ID_SUCCESS = "CAT_FETCH_BY_ID_SUCCESS";
export const CAT_FETCH_BY_ID_FAILS = "CAT_FETCH_BY_ID_FAILS";
